# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'
source 'https://github.com/CubiCasa/podspecs.git'

target 'CubiCaptureDemo_CocoaPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CubiCaptureDemo_CocoaPods
  pod 'CubiCapture', '~> 3'
end
